[project]
name = "mxspots"
version = "0.1.0"
description = "Spot Analysis for Assessing Quality of MX Diffraction Frames"
authors = [
    {name = "Michel Fodje", email = "michel4j@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "mxio  (>=2025.10.7)",
    "numpy (>=2.5.2,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1,<10.0.0",
    "matplotlib>=3.11.1,<4.0.0",
]

[project.scripts]
"mxspots.findspots" = "mxspots.cli:findspots_main"
"mxspots.score"     = "mxspots.cli:score_main"

[build-system]
requires = ["scikit-build-core>=0.10"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
build.verbose = true
cmake.build-type = "Release"
wheel.packages = ["src/mxspots"]
sdist.include = ["tests/*"]

[tool.pytest.ini_options]
pythonpath = ["src"]
